# db/seeds.rb

creator_roles = {
  "Vince Alascia" => [ "Inker" ],
  "Nina Albright" => [ "Artist" ],
  "Alfredo Alcala" => [ "Artist" ],
  "Lee J. Ames" => [ "Artist" ],
  "Murphy Anderson" => [ "Inker" ],
  "Alfred Andriola" => [ "Writer" ],
  "Ross Andru" => [ "Artist" ],
  "Everett M. Arnold" => [ "Writer" ],
  "Ruth Atkinson" => [ "Inker" ],
  "Al Avison" => [ "Artist" ],
  "Dick Ayers" => [ "Inker" ],
  "Bernard Baily" => [ "Artist" ],
  "Matt Baker" => [ "Artist" ],
  "Ken Bald" => [ "Artist" ],
  "Violet Barclay" => [ "Artist" ],
  "Ken Battefield" => [ "Inker" ],
  "C. C. Beck" => [ "Artist" ],
  "Allen Bellman" => [ "Artist" ],
  "Robert Bernstein" => [ "Writer" ],
  "Alfred Bester" => [ "Writer" ],
  "Jack Binder" => [ "Artist" ],
  "Otto Binder" => [ "Writer" ],
  "Charles Biro" => [ "Writer" ],
  "Alex Blum" => [ "Artist" ],
  "Toni Blum" => [ "Artist" ],
  "Frank Bolle" => [ "Artist" ],
  "Henry Boltinoff" => [ "Artist" ],
  "Murray Boltinoff" => [ "Writer" ],
  "Wayne Boring" => [ "Artist" ],
  "Frank Borth" => [ "Artist" ],
  "Dick Briefer" => [ "Artist" ],
  "John Broome" => [ "Writer" ],
  "Bob Brown" => [ "Artist" ],
  "Carl Burgos" => [ "Artist" ],
  "Jack Burnley" => [ "Artist" ],
  "John Buscema" => [ "Artist" ],
  "Barbara Fiske Calhoun" => [ "Writer" ],
  "Donald Clough Cameron" => [ "Writer" ],
  "Nick Cardy" => [ "Artist" ],
  "Louis Cazeneuve" => [ "Artist" ],
  "Hank Chapman" => [ "Writer" ],
  "Lillian Chestney" => [ "Artist" ],
  "Gene Colan" => [ "Artist" ],
  "Jack Cole" => [ "Artist" ],
  "L. B. Cole" => [ "Artist" ],
  "Pete Costanza" => [ "Inker" ],
  "Reed Crandall" => [ "Artist" ],
  "Mel Cummin" => [ "Artist" ],
  "Ray Cummings" => [ "Writer" ],
  "Jon D'Agostino" => [ "Inker" ],
  "Dan DeCarlo" => [ "Artist" ],
  "Dick Dillin" => [ "Artist" ],
  "Steve Ditko" => [ "Artist" ],
  "Bill Draut" => [ "Artist" ],
  "Edd Ashe" => [ "Artist" ],
  "Joe Edwards" => [ "Artist" ],
  "Eisner & Iger" => [ "Studio" ],
  "Will Eisner" => [ "Writer" ],
  "Lee Elias" => [ "Artist" ],
  "Whitney Ellsworth" => [ "Writer" ],
  "Bill Everett" => [ "Artist" ],
  "Vincent Fago" => [ "Writer" ],
  "Al Feldstein" => [ "Writer" ],
  "Martin Filchock" => [ "Artist" ],
  "Lou Fine" => [ "Artist" ],
  "Bill Finger" => [ "Writer" ],
  "Virgil Finlay" => [ "Artist" ],
  "Creig Flessel" => [ "Artist" ],
  "Gardner Fox" => [ "Writer" ],
  "Gill Fox" => [ "Artist" ],
  "Bill Fraccio" => [ "Artist" ],
  "Ramona Fradon" => [ "Artist" ],
  "Frank Frazetta" => [ "Artist" ],
  "Al Gabriele" => [ "Artist" ],
  "Frank Giacoia" => [ "Inker" ],
  "Walter B. Gibson" => [ "Writer" ],
  "Joe Gill" => [ "Writer" ],
  "John Giunta" => [ "Artist" ],
  "Sam Glanzman" => [ "Artist" ],
  "Edmond Good" => [ "Writer" ],
  "Jerry Grandenetti" => [ "Artist" ],
  "Sid Greene" => [ "Inker" ],
  "Fred Guardineer" => [ "Artist" ],
  "Paul Gustavson" => [ "Artist" ],
  "Edmond Hamilton" => [ "Writer" ],
  "Bob Haney" => [ "Writer" ],
  "Fletcher Hanks" => [ "Artist" ],
  "Harry Harrison" => [ "Writer" ],
  "Sol Harrison" => [ "Artist" ],
  "Ernie Hart" => [ "Writer" ],
  "Al Hartley" => [ "Artist" ],
  "Russ Heath" => [ "Artist" ],
  "Ray Herman" => [ "Writer" ],
  "France Herron" => [ "Writer" ],
  "Patricia Highsmith" => [ "Writer" ],
  "Alvin Hollingsworth" => [ "Artist" ],
  "Fran Hopper" => [ "Artist" ],
  "Jerry Iger" => [ "Inker" ],
  "Carmine Infantino" => [ "Artist" ],
  "Graham Ingels" => [ "Artist" ],
  "Lloyd Jacquet" => [ "Artist" ],
  "Jack Kamen" => [ "Artist" ],
  "Bob Kane" => [ "Artist" ],
  "Gil Kane" => [ "Artist" ],
  "Robert Kanigher" => [ "Writer" ],
  "George Kapitan" => [ "Writer" ],
  "George Kashdan" => [ "Writer" ],
  "Jack Katz" => [ "Artist" ],
  "Jack Keller" => [ "Artist" ],
  "Fred Kelly" => [ "Artist" ],
  "Fred Kida" => [ "Artist" ],
  "Henry C. Kiefer" => [ "Artist" ],
  "Everett Kinstler" => [ "Artist" ],
  "Jack Kirby" => [ "Artist" ],
  "George Klein" => [ "Inker" ],
  "Warren Kremer" => [ "Artist" ],
  "Joe Kubert" => [ "Artist" ],
  "Leon Lazarus" => [ "Artist" ],
  "André LeBlanc" => [ "Artist" ],
  "Stan Lee" => [ "Writer" ],
  "Harris Levey" => [ "Artist" ],
  "Alex Lovy" => [ "Artist" ],
  "Bob Lubbers" => [ "Artist" ],
  "Jesse Marsh" => [ "Artist" ],
  "Elizabeth Holloway Marston" => [ "Writer" ],
  "William Moulton Marston" => [ "Writer" ],
  "Sheldon Mayer" => [ "Writer" ],
  "Bob McCay" => [ "Artist" ],
  "Denis McLoughlin" => [ "Writer" ],
  "Al McWilliams" => [ "Artist" ],
  "Mort Meskin" => [ "Artist" ],
  "June Tarpé Mills" => [ "Writer" ],
  "Sheldon Moldoff" => [ "Artist" ],
  "Jim Mooney" => [ "Artist" ],
  "Ruben Moreira" => [ "Inker" ],
  "Win Mortimer" => [ "Artist" ],
  "Dennis Neville" => [ "Artist" ],
  "Charles Nicholas" => [ "Artist" ],
  "Norman Nodel" => [ "Artist" ],
  "Martin Nodell" => [ "Artist" ],
  "Klaus Nordling" => [ "Artist" ],
  "Paul Norris" => [ "Artist" ],
  "Irv Novick" => [ "Artist" ],
  "Leo Nowak" => [ "Artist" ],
  "Bob Oksner" => [ "Inker" ],
  "Jack Oleck" => [ "Writer" ],
  "Joe Orlando" => [ "Artist" ],
  "George Papp" => [ "Artist" ],
  "Victor E. Pazmiño" => [ "Inker" ],
  "Arthur Peddy" => [ "Artist" ],
  "Carl Pfeufer" => [ "Artist" ],
  "Arthur Pinajian" => [ "Artist" ],
  "Al Plastino" => [ "Artist" ],
  "Kin Platt" => [ "Artist" ],
  "Bob Powell" => [ "Artist" ],
  "Howard Purcell" => [ "Artist" ],
  "Fred Ray" => [ "Artist" ],
  "David Vern Reed" => [ "Writer" ],
  "Paul Reinman" => [ "Artist" ],
  "Lily Renée" => [ "Artist" ],
  "Don Rico" => [ "Writer" ],
  "Frank Robbins" => [ "Artist" ],
  "Jerry Robinson" => [ "Artist" ],
  "Ruth Roche" => [ "Artist" ],
  "Boody Rogers" => [ "Artist" ],
  "John Romita Sr." => [ "Artist" ],
  "Joe Rosen" => [ "Letterer" ],
  "John Rosenberger" => [ "Artist" ],
  "George Roussos" => [ "Inker" ],
  "Christopher Rule" => [ "Artist" ],
  "Art Saaf" => [ "Artist" ],
  "Harry Sahle" => [ "Artist" ],
  "Benjamin W. Sangor" => [ "Writer" ],
  "Norman Saunders" => [ "Artist" ],
  "Kurt Schaffenberger" => [ "Artist" ],
  "Jack Schiff" => [ "Writer" ],
  "Ira Schnapp" => [ "Letterer" ],
  "Alex Schomburg" => [ "Artist" ],
  "Ernie Schroeder" => [ "Artist" ],
  "Fred Schwab" => [ "Artist" ],
  "Julius Schwartz" => [ "Editor" ],
  "Lew Sayre Schwartz" => [ "Artist" ],
  "Mike Sekowsky" => [ "Artist" ],
  "John Severin" => [ "Artist" ],
  "Hal Sherman" => [ "Artist" ],
  "Syd Shores" => [ "Artist" ],
  "Joe Shuster" => [ "Artist" ],
  "Jerry Siegel" => [ "Writer" ],
  "Artie Simek" => [ "Letterer" ],
  "Joe Simon" => [ "Artist" ],
  "Martin Simmonds" => [ "Artist" ],
  "Frank Springer" => [ "Artist" ],
  "Alvin St. John" => [ "Artist" ],
  "William Stout" => [ "Artist" ],
  "Sam Takahashi" => [ "Artist" ],
  "Darryl Tatum" => [ "Artist" ],
  "Marv Wolfman" => [ "Writer" ],
  "George Tuska" => [ "Artist" ],
  "Vince Tuska" => [ "Artist" ],
  "Frank Tschida" => [ "Artist" ],
  "Ben Turner" => [ "Artist" ],
  "Robert Tyler" => [ "Artist" ],
  "George W. Troup" => [ "Artist" ],
  "Vincent A. Van Gogh" => [ "Artist" ],
  "Ted Van Gorder" => [ "Artist" ],
  "Jim Vadeboncoeur Jr." => [ "Writer" ],
  "Lou Wacker" => [ "Artist" ],
  "Herb Wigo" => [ "Artist" ],
  "Bill Wright" => [ "Artist" ],
  "Jack Yates" => [ "Artist" ]
}


# Run the roles seed. Run this top for creating the creators. Then uncomment the bottom to create the connections
#
#
# creator_roles.each do |creator_name, _role_names|
#   # Find or create the creator by name
#   creator = Creator.find_or_create_by(name: creator_name)

#   if creator.persisted?
#     puts "Successfully created or found creator: #{creator_name}"
#   else
#     puts "Failed to create or find creator: #{creator_name}"
#   end
# end
creator_roles.each do |creator_name, role_names|
  creator = Creator.find_by(name: creator_name)
  if creator
    puts "Processing creator: #{creator_name}"
  else
    puts "Creator not found: #{creator_name}"
  end

  role_names.each do |role_name|
    role = CreatorRole.find_by(role: role_name)
    if role
      puts "Processing role: #{role_name}"
    else
      puts "Role not found: #{role_name}"
    end

    next unless creator && role

    creator_role_creator = CreatorRolesCreator.find_or_create_by(creator_id: creator.id, creator_role_id: role.id)

    if creator_role_creator.persisted?
      puts "Created association for #{creator_name} with role #{role_name}"
    else
      puts "Failed to create association for #{creator_name} with role #{role_name}"
    end
  end
end
